version: '3.7'
services:

  nginx:
    build:
      context: ./deployment/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${DOCKER_NGINX_WEB_PORT}:80"
    volumes:
      - .:/var/www/html:Z
    depends_on:
      - fpm

  fpm:
    build:
      context: ./deployment/fpm
      args:
        DOCKER_CONTAINER_UID: ${DOCKER_CONTAINER_UID}
        DOCKER_CONTAINER_GID: ${DOCKER_CONTAINER_GID}
        APP_ENV: ${APP_ENV}
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "${DOCKER_FPM_PHP_EXTRAHOST}"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:Z
      - ./deployment/fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini


  memcached:
    image: memcached:1.6
    restart: always
    links:
      - fpm

  mysql:
    image: mysql
    ports:
        - "${DB_PORT}:3306"
    volumes:
        - "./docker/mysql/database/:/var/lib/mysql"
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
